### PR TITLE
[WIP] Release 7 0

### PR DESCRIPTION
**Pull request by WilliamBZA**

### CODE REVIEW

**Comment by kbaley** [comment]
Will this be moving over to the new build templates? I know it's not going to support .NET Core but the new build templates will work either way. If so, you _may_ need to update the .csproj files further. Details are on the top of the [checklist](https://github.com/Particular/DotNetCoreLaunch/issues/33) for moving a project to beta. Specifically the parts about the `<DebugType>`, `<DebugSymbols>`, and `<CopyLocalLockFileAssemblies>` tags.

**Comment by WilliamBZA** [comment]
@kbaley Eventually 😉

**Comment by boblangley** [comment]
PR #40 should address these issues

**Comment by boblangley** [comment]
Smoke tested NServiceBus.Ninject.7.0.0-beta0002.nupkg and pushed to Nuget

**Comment by boblangley** [comment]
Smoke tested NServiceBus.Ninject.7.0.0-beta0003.nupkg and staged to MyGet

**Comment by boblangley** [comment]
Closing this PR, RC task force will create this when ready.

**Pull request closed without merging**
