### PR TITLE
[WIP] Upgraded the Ninject container to support v6

### PR DESCRIPTION
**Pull request by WilliamBZA**
There is a lot of noise in this PR because of the acceptance tests. Should potentially have split that out into 2 separate commits.

Still to do:
 - [x] Update docs

Connects to https://github.com/Particular/NServiceBus.Ninject/issues/11

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Having intermittent failures on the acceptance tests on the build server

**Comment by WilliamBZA** [comment]
Each time the build runs, a different set of tests fail

**Comment by timbussmann** [comment]
> There is a lot of noise in this PR because of the acceptance tests. Should potentially have split that out into 2 separate commits.

please do, it will be impossible to review otherwise.

**Comment by WilliamBZA** [comment]
@timbussmann split the PR up into 2 commits. First one updates all acceptance tests, second commit updates the Ninject code.

**Comment by johnsimons** [comment]
I can look at it

**Comment by WilliamBZA** [comment]
This PR is ready for review. I will remove the WIP once the docs PRs are ready to go as well.

**Comment by WilliamBZA** [comment]
Closing this. The change to the container tests makes this pretty much useless :smile: 

blah

**Pull request closed without merging**
