### PR TITLE
Update to NSB v6

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@SimonCropp I updated to V6

**Comment by mauroservienti** [comment]
connects to #11

**Comment by SimonCropp** [comment]
@WilliamBZA do u need help with this?

**Comment by WilliamBZA** [comment]
@SimonCropp I'll know in about 45 minutes... Last outstanding problem is objects created by a child container aren't being disposed.

If this current attempt doesn't sort it out I'll ping for some help.

**Comment by timbussmann** [comment]
> objects created by a child container aren't being disposed.

which scope are they using?

**Pull request closed without merging**
